version: '3.1'

services:
  db:
    image: mariadb:10.9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db

  ledindobot:
    image: dindobot:deb-bullseye ##image personnalisée (voir Dockerfile)
    depends_on: 
      - db
    volumes:
      - ./BOT_DIR:/BOT_DIR:ro

