version: '3.1'

services:
  db:
    image: mariadb:10.9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - db_bot
      - db_apache

  phpmyadmin:
    image: phpmyadmin
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    networks:
      - db_apache
      

  ledindobot:
    image: dindobot:deb-bullseye ##image personnalisée (voir Dockerfile)
    depends_on: 
      - db
    volumes:
      - ./BOT_DIR:/BOT_DIR:ro
    networks:
      - db_bot

networks:
    db_bot:
        driver: bridge
    db_apache:
        driver: bridge



